import { v4 as uuidv4 } from "uuid";
import makzo from './assets/cover/Makzo.jpg'
import chillhopCover from './assets/cover/Chillhop.jpg';

export default function chillHop() {
  return [
    {
      name: "Oasis",
      cover: makzo,
      artist: "Makzo",
      audio: "https://mp3.chillhop.com/serve.php/?mp3=11768",
      color: ["#47609D", "#E88774"],
      id: uuidv4(),
      active: true,
    },
    {
      name: "Beaver Creek",
      cover: chillhopCover,
      artist: "Aso, Middle School, Aviino",
      audio: "https://mp3.chillhop.com/serve.php/?mp3=10075",
      color: ["#205950", "#2ab3bf"],
      id: uuidv4(),
      active: false,
    },
    {
      name: "Daylight",
      cover: chillhopCover,
      artist: "Aiguille",
      audio: "https://mp3.chillhop.com/serve.php/?mp3=9272",
      color: ["#EF8EA9", "#ab417f"],
      id: uuidv4(),
      active: false,
    },
    {
      name: "Keep Going",
      cover: chillhopCover,
      artist: "Swørn",
      audio: "https://mp3.chillhop.com/serve.php/?mp3=9222",
      color: ["#CD607D", "#c94043"],
      id: uuidv4(),
      active: false,
    },
    {
      name: "Going Back",
      cover: chillhopCover,
      artist: "Swørn",
      audio: "https://mp3.chillhop.com/serve.php/?mp3=10310",
      color: ["#335561", "#3A393E"],
      id: uuidv4(),
      active: false,
    },
    {
      name: "Bliss",
      cover: chillhopCover,
      artist: "Misha, Jussi Halme",
      audio: "https://mp3.chillhop.com/serve.php/?mp3=9248",
      color: ["#2A416D", "#E98087"],
      id: uuidv4(),
      active: false,
    },
    {
      name: "Growing Apart",
      cover: chillhopCover,
      artist: "Swørn",
      audio: "https://mp3.chillhop.com/serve.php/?mp3=9219",
      color: ["#BD3D76", "#551853"],
      id: uuidv4(),
      active: false,
    },
    {
      name: "Sails",
      cover: chillhopCover,
      artist: "Strehlow, Aylior",
      audio: "https://mp3.chillhop.com/serve.php/?mp3=9355",
      color: ["#F2C5AB", "#BE5853"],
      id: uuidv4(),
      active: false,
    },
    {
      name: "Cruisin'",
      cover: chillhopCover,
      artist: "Cloudchord, G Mills",
      audio: "https://mp3.chillhop.com/serve.php/?mp3=8200",
      color: ["#FF194A", "#41B3B3"],
      id: uuidv4(),
      active: false,
    },
    {
      name: "Maple Leaf Pt.2",
      cover: chillhopCover,
      artist: "Philanthrope",
      audio: "https://mp3.chillhop.com/serve.php/?mp3=10243",
      color: ["#CA483B", "#682C24"],
      id: uuidv4(),
      active: false,
    },
    {
      name: "Nightfall",
      cover: chillhopCover,
      artist: "Aiguille",
      audio: "https://mp3.chillhop.com/serve.php/?mp3=9148",
      color: ["#EF8EA9", "#ab417f"],
      id: uuidv4(),
      active: false,
    },
    {
      name: "Reflection",
      cover: chillhopCover,
      artist: "Swørn",
      audio: "https://mp3.chillhop.com/serve.php/?mp3=9228",
      color: ["#CD607D", "#c94043"],
      id: uuidv4(),
      active: false,
    },
    {
      name: "Leaving For Good",
      cover: chillhopCover,
      artist: "Hanz",
      audio: "https://mp3.chillhop.com/serve.php/?mp3=8264",
      color: ["#90B4AA", "#F2AE87"],
      id: uuidv4(),
      active: false,
    },
    {
      name: "Eastway",
      cover: chillhopCover,
      artist: "Dontcry, Nokiaa",
      audio: "https://mp3.chillhop.com/serve.php/?mp3=9071",
      color: ["#B442A1", "#F54F7A"],
      id: uuidv4(),
      active: false,
    },
    {
      name: "Wake up",
      cover: chillhopCover,
      artist: "Evil Needle",
      audio: "https://mp3.chillhop.com/serve.php/?mp3=8285",
      color: ["#A35CA0", "#EE8D66"],
      id: uuidv4(),
      active: false,
    },
    {
      name: "Under the City Stars",
      cover: chillhopCover,
      artist: "Aso, Middle School, Aviino",
      audio: "https://mp3.chillhop.com/serve.php/?mp3=10074",
      color: ["#205950", "#2ab3bf"],
      id: uuidv4(),
      active: false,
    },
    {
      name: "Velocities",
      cover: chillhopCover,
      artist: "Sleepy Fish",
      audio: "https://mp3.chillhop.com/serve.php/?mp3=3524",
      color: ["#74c7b4", "#1d6d92"],
      id: uuidv4(),
      active: false,
    },
    {
      name: "Deeper",
      cover: chillhopCover,
      artist: "Aviino",
      audio: "https://mp3.chillhop.com/serve.php/?mp3=10460",
      color: ["#C668B2", "#4D92D7"],
      id: uuidv4(),
      active: false,
    },
  ];
}